AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  DispatchAlerts:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::xxxx:role/lambda_sns_alerting_role'
      Events:
        SNS1:
          Type: SNS
          Properties:
            Topic:
              Ref: SNSTopic1
      Environment:
        Variables:
          sodPhoneNumber: '+4919999999999'
          sodPhoneNumber_org: '+4919999999999'
  SNSTopic1:
    Type: 'AWS::SNS::Topic'
